name: Deploy Package to NPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Packages
        run: npm i
        run: npm ci

  Publish Package:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJs
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Setup Github Credentials
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email gh-actions-${GITHUB_ACTOR}@github.com
    
      - name: Bump Version of package.json
      - uses: ramonpaolo/bump-version@v2.3.1
        with: 
          tag: ${{ github.ref_name }} # Accessing the context and get the reference_name, that in this case, is the tag that you created(ex: v1.0.0)
          commit: true
          branch_to_push: 'master'

        run: npm version patch
      
      - name: Publish package to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
